/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vieww;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdbcBack.model.Cadastro;
import jdbcBack.model.ProdutoDAO;

/**
 *
 * @author User
 */
public class Listagem extends javax.swing.JFrame {

    /**
     * Creates new form FilmeListagem
     */
    public Listagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        BotoNovo = new javax.swing.JButton();
        BotoExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotoSair = new javax.swing.JButton();
        BotoSuporte = new javax.swing.JButton();

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pane1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        tabela.setModel(montarTabela());
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pane1.setViewportView(tabela);

        getContentPane().add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 642, 350));

        BotoNovo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BotoNovo.setText("+Novo ");
        BotoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BotoNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        BotoExcluir.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BotoExcluir.setText("Excluir");
        BotoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BotoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, 30));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("Listagem");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Área de Trabalho\\Projects\\ProgetoFina\\css\\img\\Logos\\imagem_2024-08-11_193703035-removebg-preview.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 642, -1));

        BotoSair.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BotoSair.setForeground(new java.awt.Color(255, 51, 51));
        BotoSair.setText("Sair");
        BotoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 110, -1));

        BotoSuporte.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BotoSuporte.setText("Suporte");
        BotoSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoSuporteActionPerformed(evt);
            }
        });
        getContentPane().add(BotoSuporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoNovoActionPerformed
        TelaCadastro pl = new TelaCadastro();
        pl.setVisible(true);
    }//GEN-LAST:event_BotoNovoActionPerformed

    private void BotoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoExcluirActionPerformed
        int id = getPosicao();

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro? ");
        if (resposta == 0) {
            ProdutoDAO.excluir(id);
        }

        //Para reexibir e atualizar a tabela na mesma tela
        tabela.setModel(montarTabela());
        pane1.setViewportView(tabela);
    }//GEN-LAST:event_BotoExcluirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BotoSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoSuporteActionPerformed
       EnviarFeedback pl = new EnviarFeedback();
       pl.setVisible(true);
    }//GEN-LAST:event_BotoSuporteActionPerformed

    private void BotoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoSairActionPerformed
        dispose();
    }//GEN-LAST:event_BotoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela() {
    String[] colunas = {"id", "Funcionario", "Registro", "Cargo"};

    // Criamos a tabela
    DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

    List<Cadastro> lista = ProdutoDAO.listarTodos();

    for (Cadastro p : lista) {
        String[] linha = {
            Integer.toString(p.getId()),
            p.getFuncionario(), // Corrigido para getFuncionario
            Cadastro.converterParaJava(p.getRegistro()), // Corrigido para LocalDate
            p.getCargo() // Corrigido para getCargo
        };

        tabela.addRow(linha);
    }

    return tabela;
    }

    private int getPosicao() {
        int posicao = tabela.getSelectedRow();
        if (posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
        return Integer.parseInt((String) tabela.getValueAt(posicao, 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoExcluir;
    private javax.swing.JButton BotoNovo;
    private javax.swing.JButton BotoSair;
    private javax.swing.JButton BotoSuporte;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane pane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
